apiVersion: apps/v1
kind: Deployment
metadata:
 name: ai-prod-demo
 labels:
   app: ai-prod-demo
spec:
 replicas: 1
 selector:
   matchLabels:
     app: ai-prod-demo
 template:
   metadata:
     labels:
       app: ai-prod-demo
   spec:
     containers:
       - name: ai-prod-demo
         image: registry.digitalocean.com/rs-general/ai-prod-demo:latest
         imagePullPolicy: Always
         ports:
           - containerPort: 8000
         readinessProbe:
           httpGet:
             path: /health
             port: 8000
           initialDelaySeconds: 5
           timeoutSeconds: 5
           periodSeconds: 5
       - name: prod-demo-ui
         image: registry.digitalocean.com/rs-general/prod-demo-ui:latest
         imagePullPolicy: Always
         ports:
           - containerPort: 8501
         readinessProbe:
           httpGet:
             path: /healthz
             port: 8501
           initialDelaySeconds: 5
           timeoutSeconds: 5
           periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-prod-demo-service
spec:
  type: ClusterIP
  selector:
    app: ai-prod-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-prod-demo-ui-service
spec:
  type: LoadBalancer
  selector:
    app: ai-prod-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
