apiVersion: apps/v1
kind: Deployment
metadata:
 name: ai-prod-demo-ui
 labels:
   app: ai-prod-demo-ui
spec:
 replicas: 1
 selector:
   matchLabels:
     app: ai-prod-demo-ui
 template:
   metadata:
     labels:
       app: ai-prod-demo-ui
   spec:
     containers:
       - name: prod-demo-ui
         image: registry.digitalocean.com/rs-general/prod-demo-ui:latest
         imagePullPolicy: Always
         ports:
           - containerPort: 8501
         readinessProbe:
           httpGet:
             path: /healthz
             port: 8501
           initialDelaySeconds: 5
           timeoutSeconds: 5
           periodSeconds: 5
