apiVersion: v1
kind: Service
metadata:
  name: ai-prod-demo-ui-service
spec:
  type: LoadBalancer
  selector:
    app: ai-prod-demo-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
